Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # web01
  config.vm.define "web01" do |web|
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip: "192.168.56.10"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # db01
  config.vm.define "db01" do |db|
    db.vm.hostname = "db01"
    db.vm.network "private_network", ip: "192.168.56.20"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # monitor01
  config.vm.define "monitor01" do |monitor|
    monitor.vm.hostname = "monitor01"
    monitor.vm.network "private_network", ip: "192.168.56.30"
    monitor.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end
