---
- hosts: web
  become: yes
  roles:
    - common
    - nginx
    - node_exporter

- hosts: db
  become: yes
  roles:
    - common
    - mysql
    - node_exporter

- hosts: monitor
  become: yes
  roles:
    - common
    - monitor
    - grafana
