---
- hosts: web
  become: yes
  roles:
    - common
    - nginx
    - node_exporter
    - filebeat

- hosts: db
  become: yes
  roles:
    - common
    - mysql
    - node_exporter
    - filebeat

- hosts: monitor
  become: yes
  roles:
    - common
    - monitor
    - grafana
    - elasticsearch
    - kibana
    
